### ISSUE TITLE
Add deprecation warnings for Python 2.4

### ISSUE THREAD

**Issue by drkjam** [netaddr/netaddr#135]
The next release (0.7.19) will be the last to officially support Python 2.4.x

**Why?**

It is time to move on. The codebase need to be able to modernise and move forward. Hopefully this will not disenfranchise too many users.

**How Will This Affect My Code?**

The forthcoming 0.7.19 release will raise deprecation warnings when Python 2.4.x is detected. Subsequent releases will move to 0.8.x and solidify this change by raising a hard exception.

**Comment by drkjam** [comment]
This deprecation is a signal to users that we are moving away from 2.4. The next release will raise an exception on Python versions lower than 2.5 (see [Issue 136](https://github.com/drkjam/netaddr/issues/136))

**Comment by jstasiak** [comment]
The support has been dropped a while ago, we can close this now.
