### ISSUE TITLE
Raise RuntimeError on Python interpreters < 2.5.x on netaddr 0.8.x

### ISSUE THREAD

**Issue by drkjam** [netaddr/netaddr#136]
The next **major** release (0.8.0) ends support Python 2.4.x.

**Why?**

It is time to move on. The codebase need to be able to modernise and move forward. Hopefully this will not disenfranchise too many users. If you need to use netaddr you can continue to use older releases until you can upgrade to a more recent version of Python (2.5 or better).

**How Will This Affect My Code?**

You will get a RuntimeError exception raised if you are running netaddr under Python 2.4.x or lower.

**Comment by jstasiak** [comment]
We've actually dropped support for multiple Python versions since then. Closing as done.
