### ISSUE TITLE
Membership check of `IPNetwork` in `IPRange` may be broken

### ISSUE THREAD

**Issue by reutsharabani** [netaddr/netaddr#157]
I think the membership check of `IPNetwork` in `IPRange` may be broken. I've added some tests and a fix.

Example:

    net = IPNetwork('10.0.0.0/30')
    rng = IPRange(net.first, net.last)
    net in rng

Produces:

> False

To make sure:

    for ip in net:
        print ip in rng

Produces:

    True
    True
    True
    True

I've added a bit more details here: http://stackoverflow.com/questions/42929258/wrong-result-in-netaddrs-iprange-contains-in-operator

**Comment by yoav-orca** [comment]
Git Biten by this too:
```python
>>> IPNetwork("0.0.0.0/0") in IPRange(0, 2**32-1)
False
```

It seems that there's an off by one in `other_next_start = other_start + (1 << shiftwidth)` calculation

**Comment by reutsharabani** [comment]
@yoav-orca  I already fixed this, it should be merged as far as I remember so probably just need to update version.

**Comment by jstasiak** [comment]
I saw no good reason for the existing behavior so I changed it. New version to be released in the near future.

**Comment by jstasiak** [comment]
Fix released in 1.1.0.
