### ISSUE TITLE
IP Port

### ISSUE THREAD

**Issue by jeffg2k** [netaddr/netaddr#175]
I have netaddr in a piece of software I'm working with and it fails when a user tries to include a port with the ip.  192.168.1.1:8080 for example.  Does netaddr support a method of storing the port or is this something I should do in the application itself?

**Comment by tyler-8** [comment]
Ports have nothing to do with IP addressing so I'm not sure it'd make sense for netaddr to do port handling. That kind of logic would go in your application.

**Comment by tpickle-py** [comment]
Since IPv6 uses ':' I would make sure the code netaddr is getting is a valid IP before depending on it.

I would implement a simple check:

```python
from netaddr import IPAddress

def checkip(ip):
    if isinstance(ip,IPAddress):
        return True
    return False
```

**Comment by jstasiak** [comment]
I think this is out of scope for this library, but please reopen if you believe you have a convincing argument.
