### ISSUE TITLE
can netaddr convert a IPv4 or IPv6 network in CIDR format?

### ISSUE THREAD

**Issue by randomgambit** [netaddr/netaddr#176]
Hello,

Thanks for this great package! I wonder if `netaddr` can convert a IPv4 or IPv6 network in CIDR format into a dataframe of I.P addresses. I am working with the free `geoip2 ASN` csv from Maxmind, but I cant match a single IP address with something in CIDR format...

Any ideas?
Thanks!

**Comment by tyler-8** [comment]
The [documentation](https://netaddr.readthedocs.io/en/latest/tutorial_01.html#list-operations) should be helpful.

**Comment by randomgambit** [comment]
thanks for the link!

**Comment by jstasiak** [comment]
I think this is resolved, please reopen if I misread it.
