### ISSUE TITLE
support IABs in the 40:D8:55 OUI

### ISSUE THREAD

**Issue by brianmaissy** [netaddr/netaddr#190]
currently only mac addresses in the 00:50:C2 OUI are considered to have an IAB, but IABs are also allocated in the 40:D8:55 IUI (since 2012, according to [wikipedia](https://en.wikipedia.org/wiki/MAC_address#Address_details)).

Happy to open a PR.

**Comment by brianmaissy** [comment]
bump?

**Comment by brianmaissy** [comment]
@drkjam anyone there?

**Comment by brianmaissy** [comment]
@snordhausen?

**Comment by jstasiak** [comment]
#191 is merged now.

**Comment by jstasiak** [comment]
This has been fixed in 0.8.0.
