### ISSUE TITLE
oui databases are outdated

### ISSUE THREAD

**Issue by brianmaissy** [netaddr/netaddr#198]
the oui databases are woefully outdated (last updated more than 3 years ago).
I have a PR open to update them for a few months already, see #189 .
I would very much appreciate it getting merged and a verison released.

**Comment by jstasiak** [comment]
Fixed in 0.7.20.

**Comment by brianmaissy** [comment]
Thanks @jstasiak ! I see you've been very active recently, does this mean the project is going to be actively maintained again? If that's the case, I have another PR open (https://github.com/netaddr/netaddr/pull/191) and would be happy to continue contributing, if that's something you're looking for.

**Comment by jstasiak** [comment]
As long as time and my knowledge allow me I'll try to review stuff and address issues every now and then. I need to educate myself before I can review #191 but in general yes, if you have some more patches it'll be cool to receive them, any and all help is appreciated. :)
