### ISSUE TITLE
N log N complexity instead of linear

### ISSUE THREAD

**Issue by hnarkaytis** [netaddr/netaddr#205]
https://github.com/netaddr/netaddr/blob/ebf714601e8cd6234575422f876d4d579b202b1a/netaddr/ip/__init__.py#L1663
Sorting is used only for finding min and max values in the sequence. Potentially input set might contain billions of elements and sorting will take unreasonable time.

**Comment by brianmaissy** [comment]
@jstasiak happy to open a PR for this if it's something you would merge

**Comment by jstasiak** [comment]
Yes, absolutely, it'd be cool.

**Comment by jstasiak** [comment]
This has been fixed in 0.8.0.
