### ISSUE TITLE
Release 0.7.20 broken ansible filter ips_in_ranges

### ISSUE THREAD

**Issue by LuckySB** [netaddr/netaddr#213]
Ansible 2.8.12, netaddr 0.7.20, 

Run ansible scenario for install ceph https://github.com/ceph/ceph-ansible/tree/v4.0.24 and get error:
`msg: The ips_in_ranges filter requires python's netaddr be installed on the ansible controller.`

Downgrade netaddr to 0.7.19 and all work fine

**Comment by jstasiak** [comment]
Thank you for the information. The following information is needed for this report to be actionable:

* The exact Python version
* The version of the operating system running it
* A description of what's broken on `netaddr` side. If there's some internal Ansible error silenced that would be helpful to see (including full stack trace). The error message you quoted is generated by Ansible and I don't know how it relates to the underlying issue or what the issue actually is.

**Comment by jstasiak** [comment]
Actually I suspect you're on Python < 3.7 and the `importlib-resources` dependency (required starting with `netaddr` 0.7.20) is not present, resulting in an `ImportError` and Ansible interprets that as `netaddr` missing.

**Comment by jstasiak** [comment]
@LuckySB have you resolved this issue or is it still breaking things for you?

**Comment by jstasiak** [comment]
I'll assume there's no issue on our side. Please reopen if there's any new information about this that suggests otherwise.
