### ISSUE TITLE
No longer supports python 3.5

### ISSUE THREAD

**Issue by rbricheno** [netaddr/netaddr#219]
Because this depends on importlib_resources, and they dropped support for python < 3.6, this is now broken for 3.5 too.

https://github.com/python/importlib_resources/pull/202/files/bed6a81b44e10deca50a0d744ee1f3225e30cd28

For search engines, you might see this error:
`AttributeError: module 'os' has no attribute 'PathLike'`

**Comment by jstasiak** [comment]
Hey, it's not really broken, when on Python 3.5 just install the last supported `importlib_resources` version (and keep in mind the Python 3.5 support in `netaddr` is deprecated anyway).

**Comment by rbricheno** [comment]
Mea culpa. My Ubuntu 16.04 machines had got into a state where they'd installed a version of zipp and importlib_resources that they never should. I upgraded pip and was then able to solve the problem as follows:
```
python3 -m pip install --upgrade pip
python3 -m pip uninstall zipp
python3 -m pip install zipp
python3 -m pip uninstall importlib_resources
python3 -m pip install importlib_resources
```
I'm sure this is not a netaddr issue.

**Comment by jstasiak** [comment]
Cheers, good to hear you got it working in the end.
