### ISSUE TITLE
Proposing a PR to fix a few small typos

### ISSUE THREAD

**Issue by timgates42** [netaddr/netaddr#233]
# Issue Type

[x] Bug (Typo)

# Steps to Replicate and Expected Behaviour

- Examine netaddr/ip/sets.py and observe `mergable`, however expect to see `mergeable`.
- Examine netaddr/strategy/eui64.py and observe `indentifier`, however expect to see `identifier`.
- Examine netaddr/tests/strategy/test_ipv6_strategy.py and observe `visibile`, however expect to see `visible`.
- Examine netaddr/ip/sets.py and observe `subsequents`, however expect to see `subsequent`.
- Examine netaddr/ip/__init__.py and observe `indentifying`, however expect to see `identifying`.
- Examine netaddr/eui/__init__.py and observe `addressses`, however expect to see `addresses`.

# Notes

Semi-automated issue generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

To avoid wasting CI processing resources a branch with the fix has been
prepared but a pull request has not yet been created. A pull request fixing
the issue can be prepared from the link below, feel free to create it or
request @timgates42 create the PR. Alternatively if the fix is undesired please
close the issue with a small comment about the reasoning.

https://github.com/timgates42/netaddr/pull/new/bugfix_typos

Thanks.

**Comment by jstasiak** [comment]
A lot of typos fixed in 06c7633d1b134aa7e9449e84ec45856f84208080 semi-recently so I'll close this, thank you anyway.
