### ISSUE TITLE
how to  express wildcard like 1.0.1.0/0.255.0.255

### ISSUE THREAD

**Issue by Black4T2** [netaddr/netaddr#238]
wildcard ip like 1.0.1.0/0.255.0.255

**Comment by jstasiak** [comment]
Is this a documented format? I have to admit I'm not familiar with it.

**Comment by Black4T2** [comment]
Hi，thanks for replay. 
the wildcard format like 1.0.1.0/0.255.0.255 is very common in many network or security devices such as cisco switch(router,asa), huawei switch(router,usg), juniper switch(router, srx) and so on.

**Comment by Black4T2** [comment]
i
