### ISSUE TITLE
When using mac_unix dialect, the mac addy appears trims off two zeros are next to each other.

### ISSUE THREAD

**Issue by 0foo** [netaddr/netaddr#245]
<img width="251" alt="Screen Shot 2022-05-17 at 7 57 18 PM" src="https://user-images.githubusercontent.com/6382763/168948113-378cd343-8069-4534-9ef3-7ea1d8be8938.png">

**Comment by jstasiak** [comment]
Hey @0foo, thank you for the report. That's intentional. You can use `mac_unix_expanded` if you need the leading zeros.

See https://github.com/netaddr/netaddr/pull/229#issuecomment-1872150981
