### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by psmoros** [netaddr/netaddr#273]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@amammad) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by jstasiak** [comment]
Hey @psmoros, @amammad – thank you for the information.

Feel free to contact me using the `maintainer_email` listed in `setup.py` with CC to `author_email`.

**Comment by psmoros** [comment]
Thanks for your quick response @jstasiak :) I just dispatched the email let me know if you've received it.

PS: Our cc function is lagging, do you mind forwarding the email to the author yourself? <3
