### ISSUE TITLE
new release?🤔

### ISSUE THREAD

**Issue by kloczek** [netaddr/netaddr#322]
https://github.com/netaddr/netaddr/compare/0.9.0...master shows 47 commits since last release.
I think that it would be good to flush those commits as new release.
Any plans to do that soon? 🤔

**Comment by jstasiak** [comment]
Hi, I have a few more changes to add before releasing a new version, I should have them in place in a week or so.

**Comment by jstasiak** [comment]
Version 0.10.0 is out now.

**Comment by kloczek** [comment]
Just checked my automation and it was able successfully process github new release notification producing automatically new version of th package.
Thank you 👍
