### ISSUE TITLE
invalid escape sequence in ip\nmap.py

### ISSUE THREAD

**Issue by HansAarneLiblik** [netaddr/netaddr#329]
After upgrading to v0.10.0 our pytest (with coverage) fails

```
  File "/app/.venv/lib/python3.11/site-packages/netaddr/__init__.py", line 31, in <module>
    from netaddr.ip.nmap import valid_nmap_range, iter_nmap_range
  File "/app/.venv/lib/python3.11/site-packages/netaddr/ip/nmap.py", line 105
    """
    ^^^
SyntaxError: invalid escape sequence '\*'
```

It seems like `:param \*nmap_target_spec:` is not a valid docstring

`valid_nmap_range` has proper docstring

![image](https://github.com/netaddr/netaddr/assets/5418540/140cb0b1-26eb-43ad-a5b8-ab70030e7601)

`iter_nmap_range` does not have a proper docstring (as you can't escape the asterisk with backslash)

![image](https://github.com/netaddr/netaddr/assets/5418540/1e53f44e-93e7-4615-ac25-390a98505c29)

I think you need to use `:param nmap_target_spec:` instead of `:param \*nmap_target_spec:`

**Comment by jstasiak** [comment]
Thank you, fixed in https://github.com/netaddr/netaddr/pull/331 and released in 0.10.1 just now.

**Comment by HansAarneLiblik** [comment]
While that may fix the syntax warning, the IDE docstring would still be incorrect. IMO you need to drop the asterisk all together

**Comment by jstasiak** [comment]
Thanks for the note, it looks all right to me.
