### ISSUE TITLE
Add -j option to netaddr info CLI

### ISSUE THREAD

**Issue by jlshix** [netaddr/netaddr#378]
A CLI to show network info is awesome!

But we may still need a better output format for further data processing.

The `ip -j` command is a good reference, which formats all subcommand output to json.

e.g. `ip -j route | jq . > local_routes.json`

**Comment by jstasiak** [comment]
Hey, I appreciate the need for something like this but this command is intentionally not supposed to provide any kind of stable output, at least for now – it's just for human consumption and I'm experimenting on it to an extent.

If you need any kind of stable and structured output then I think the best option is just to do the processing you want in Python and use the netaddr API (including dumping data as JSON for further processing if that's needed).
