### ISSUE TITLE
len(IPSet()) fails on python3

### ISSUE THREAD

**Issue by Psykar** [netaddr/netaddr#46]
> > > len(IPSet())
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "./netaddr/ip/sets.py", line 612, in **len**
> > >     if size > _sys.maxint:
> > > AttributeError: 'module' object has no attribute 'maxint'

The same happens for list(IPSet())

> > > list(IPSet())
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "./netaddr/ip/sets.py", line 612, in **len**
> > >     if size > _sys.maxint:
> > > AttributeError: 'module' object has no attribute 'maxint'

**Comment by nlamirault** [comment]
Already present in Python 3.3 : 

```bash
$> pip freeze|grep netaddr
netaddr==0.7.14
```


```
Python 3.3.6 (default, Oct 21 2014, 16:08:44) 
[GCC 4.8.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import netaddr
>>> len(netaddr.IPSet())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vagrant/foo/.tox/py33/lib/python3.3/site-packages/netaddr/ip/sets.py", line 518, in __len__
    if size > _sys.maxint:
AttributeError: 'module' object has no attribute 'maxint'
```
