### ISSUE TITLE
Unpickling Bug in IPSet

### ISSUE THREAD

**Issue by LuizOz** [netaddr/netaddr#7]
Hi,

Im trying to pickle and unpickle an array of IPSets and I'm getting this:

```
nodes = cPickle.load(file)
```

  File "/usr/lib/python2.5/site-packages/netaddr-0.7.5-py2.5.egg/netaddr/ip/sets.py", line 94, in **setstate**
    module = _ipv4
NameError: global name '_ipv4' is not defined
# 

I've made some changes at the code and removed that _ipv4 stuff:

```
    #TODO: this needs to be optimised.
    self._cidrs = {}
    for cidr_tuple in state:
        value, prefixlen, version = cidr_tuple

        if version != 4 and version != 6:
            raise ValueError('unpickling failed for object state %s' \
                % str(state))

        if 0 <= prefixlen:
            cidr = IPNetwork((value, prefixlen), version)
            self._cidrs[cidr] = True
        else:
            raise ValueError('unpickling failed for object state %s' \
                % str(state))
```
# 

I dont wanna mess up with the code, but any reason to use that _ipv4 and _ipv6 instead of a simple if to check the versions and pass to the IPNetwork function ?

**Comment by vipshek** [comment]
Hi there,

Seems like the line of code used to fix this issue was removed from the file, so the issue is back. Here's the commit that removed the line (https://github.com/drkjam/netaddr/commit/cdc27bfe474276cda34090eb1231cf93f2404771).
